package utils

import (
	"io/ioutil"
	"os"
	"time"

	"massnet.org/mass-wallet/logging"
	"massnet.org/mass-wallet/massutil"
)

func GenerateTLSCertPair(certPath, keyPath string) error {
	logging.VPrint(logging.INFO, "Generating TLS certificates...", logging.LogFormat{
		"cert": certPath,
		"key":  keyPath,
	})

	// Generate cert pair.
	org := "masswallet autogenerated cert"
	validUntil := time.Now().Add(time.Hour * 24 * 365 * 10)
	cert, key, err := massutil.NewTLSCertPair(org, validUntil, nil)
	if err != nil {
		return err
	}

	// Write cert and (potentially) the key files.
	err = ioutil.WriteFile(certPath, cert, 0700)
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(keyPath, key, 0700)
	if err != nil {
		rmErr := os.Remove(certPath)
		if rmErr != nil {
			logging.VPrint(logging.WARN, "Cannot remove written certificates", logging.LogFormat{"error": rmErr})
		}
		return err
	}
	logging.VPrint(logging.INFO, "Done generating TLS certificates", logging.LogFormat{})
	return nil
}
